version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - PORT=${APP_PORT}
        - NODE_ENV=${NODE_ENV}
    user: node
    working_dir: /home/node/app
    env_file:
      - ./.env
    volumes:
      - .:/home/node/app
      # - /home/node/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - mynet
    command: "yarn start:dev"

  mongo:
    image: mongo:3.6
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - db-data:/data/db
    networks:
      - mynet

volumes:
  db-data:

networks:
  mynet:
